### ISSUE TITLE
WeaponsMechanicsCosmetics doesnt working

### ISSUE THREAD

**Issue by LasurkaXD** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#40]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [x] I have asked for help

### Current Behavior

[17:57:18 ERROR]: [WeaponMechanicsCosmetics] Error initializing plugin 'WeaponMechanicsCosmetics-3.0.1.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalArgumentException: Resource was null, make sure you put in the correct path!
        at me.deecaad.core.utils.FileUtil.copyResourcesTo(FileUtil.java:50) ~[MechanicsCore-3.0.4.jar:?]
        at me.cjcrafter.weaponmechanicscosmetics.WeaponMechanicsCosmetics.onLoad(WeaponMechanicsCosmetics.java:76) ~[WeaponMechanicsCosmetics-3.0.1.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Expected Behavior

Trying to download another versions below 3.0.1

### Steps To Reproduce

Idk?

### Frequency

When server strating, also after /wm reload this warn:
[17:57:18 ERROR]: [WeaponMechanicsCosmetics] Error initializing plugin 'WeaponMechanicsCosmetics-3.0.1.jar' in folder 'plugins' (Is it up to date?)
java.lang.IllegalArgumentException: Resource was null, make sure you put in the correct path!
        at me.deecaad.core.utils.FileUtil.copyResourcesTo(FileUtil.java:50) ~[MechanicsCore-3.0.4.jar:?]
        at me.cjcrafter.weaponmechanicscosmetics.WeaponMechanicsCosmetics.onLoad(WeaponMechanicsCosmetics.java:76) ~[WeaponMechanicsCosmetics-3.0.1.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.loadPlugins(CraftServer.java:524) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:310) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Version and Log

![зображення](https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/assets/129551196/87702080-26a6-4986-af9d-d1024c09f315)

### Anything else?

Nothing.

**Comment by CJCrafter** [comment]
Join our discord for support:
1. Use #verification
2. Verify that you have purchased WMC
3. Send your `latest.log` file in #weaponmechanicscosmetics-support

**Comment by LasurkaXD** [comment]
> Join our discord for support:
> 
>     1. Use #verification
> 
>     2. Verify that you have purchased WMC
> 
>     3. Send your `latest.log` file in #weaponmechanicscosmetics-support

I cant join to ur server and report this problem here

**Comment by CJCrafter** [comment]
The problem you are experiencing is suspicious, to say the least, and usually a result of having cracked plugins/viruses on your server. Your refusal to verify your account is doubly suspicious.

**Comment by LasurkaXD** [comment]
> The problem you are experiencing is suspicious, to say the least, and usually a result of having cracked plugins/viruses on your server. Your refusal to verify your account is doubly suspicious.

Bruh, I just cant join the server. Maybe I have ban, idk. Just error "Oops... Unable to accept invitation"

**Comment by CJCrafter** [comment]
![image](https://github.com/WeaponMechanics/WeaponMechanicsCosmeticsWiki/assets/43940682/2973167c-22e5-4dde-8bd7-e4bb7e7f6aef)
This you? 

If you have actually purchased a License, send me a message on Spigot and I will sort this out.

**Comment by LasurkaXD** [comment]
> ![image](https://user-images.githubusercontent.com/43940682/277132988-2973167c-22e5-4dde-8bd7-e4bb7e7f6aef.png) This you?
> 
> If you have actually purchased a License, send me a message on Spigot and I will sort this out.

This is my old account, but I don't use WeaponsMechanics 2 years ago when I used this account. Also I don`t using a pirated versions just cuz it have hacks bruuuuuuh

**Comment by LasurkaXD** [comment]
And Idk where is cracked plugins huh

**Comment by LasurkaXD** [comment]
> ![image](https://user-images.githubusercontent.com/43940682/277132988-2973167c-22e5-4dde-8bd7-e4bb7e7f6aef.png) This you?
> 
> If you have actually purchased a License, send me a message on Spigot and I will sort this out.

Hi. Im home. My username on spigot is h3nda. Pls unban me idk why I get banned but pls unban
